apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- ./deployment-patch.yaml
images:
- name: giangle197/demo-web-app
  newTag: a6538ed5ca95272a8fe3bf994ffff4275ab79e09
- name: giangle197/demo-api-app
  newTag: a6538ed5ca95272a8fe3bf994ffff4275ab79e09
