apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../manifest2

images:
- name: giangle197/demo-web-app
  newName: giangle197/demo-web-app
  newTag: v1
- name: giangle197/nginx
  newTag: v1
patches:
- path: deployment-patch.yaml
