apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- ./deployment-patch.yaml
images:
- name: giangle197/demo-api-app
  newName: giangle197/demo-api-app
  newTag: v3
- name: giangle197/demo-web-app
  newName: giangle197/demo-web-app
  newTag: v3
