version: 0.2

env:
  variables:
    DOCKERHUB_NAME: "dangvu1971998@gmail.com"
    REPOSITORY_URI: "https://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/giang-manifest-demo"
    REGISTRY: "giangle197"

  secrets-manager:
    passwd: "arn:aws:secretsmanager:ap-southeast-2:179623033511:secret:demo/CodeBuild/dockerhub_passwd-TyEpPn"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing kustomize...
      - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      - mv kustomize /usr/local/bin/
      # - apt-get update && apt-get install -y 
      # - echo Installing AWS CLI v2...
      # - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      # - unzip awscliv2.zip
      # - ./aws/install


  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $passwd
      - PASSWORD=$(echo $passwd | grep -o '"DOCKERHUB_PASSW":"[^"]*' | cut -d '"' -f 4)
      - echo $PASSWORD | docker login --username $DOCKERHUB_NAME --password-stdin

  build:
    commands:
      - echo Build started on `date`
      - echo Cloning repository...
      - echo git clone ${REPOSITORY_URI}
      - git clone https://github.com/Legiang98/multi-container-app.git


      # - git clone ${REPOSITORY_URI}
      - cd ./giang-manifest-demo/overlays/dev

      - echo Updating kustomization.yaml with new image tag...
      - kustomize edit set image giangle197/demo-web-app=${REGISTRY}/demo-web-app:test01  # ${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - kustomize edit set image giangle197/demo-api-app=${REGISTRY}/demo-api-app:test01   #${CODEBUILD_RESOLVED_SOURCE_VERSION}


  post_build:
    commands:
      - echo Build completed on `date`
      - echo Committing and pushing changes...
      - git config --global user.email "gianglecodebuild@tech.com"
      - git config --global user.name "Gianglv"
      # - git remote add origin ssh://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/giang-manifest-demo
      - git add .
      - git commit -m "Update kustomization with new image tags"
      - git push origin main

artifacts:
  files: imagedefinitions.json