version: 0.2

env:
  variables:
    DOCKERHUB_NAME: "dangvu1971998@gmail.com"
    REPOSITORY_URI: "https://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/giang-manifest-demo"
    REGISTRY: "giangle197"

  secrets-manager:
    passwd: "arn:aws:secretsmanager:ap-southeast-2:179623033511:secret:demo/CodeBuild/dockerhub_passwd-TyEpPn"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing kustomize...
      - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      - mv kustomize /usr/local/bin/

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $passwd
      - PASSWORD=$(echo $passwd | grep -o '"DOCKERHUB_PASSW":"[^"]*' | cut -d '"' -f 4)
      - echo $PASSWORD | docker login --username $DOCKERHUB_NAME --password-stdin

  build:
      commands:
        - echo Build started on `date`
        - echo Cloning repository...
        - git clone ${REPOSITORY_URI}
        - cd your-repo-name/overlays/dev

        - echo Updating kustomization.yaml with new image tag...
        - kustomize edit set image giangle197/demo-web-app=${REGISTRY}/demo-web-app:${CODEBUILD_RESOLVED_SOURCE_VERSION}
        - kustomize edit set image giangle197/demo-api-app=${REGISTRY}/demo-api-app:${CODEBUILD_RESOLVED_SOURCE_VERSION}


  post_build:
    commands:
      - echo Build completed on `date`
      - echo Committing and pushing changes...
      - git remote add origin ssh://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/giang-manifest-demo
      - git add .
      - git commit -m "Update kustomization with new image tags"
      - git push origin main

artifacts:
  files: imagedefinitions.json