apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- deploy1.yaml
- hpa-cpu.yaml
- ingress.yaml
- secret.yaml
- service.yaml
- storageclass-vpc.yaml
- web-api-config-map.yml
- web-config-map.yml

patchesStrategicMerge:
- deployment-patch.yaml
images:
- name: giangle197/demo-api-app
  newName: giangle197/demo-api-app
  newTag: v1
- name: giangle197/demo-web-app
  newName: giangle197/demo-web-app
  newTag: 1e296de72e48c93414be7ad883b00a1332038330
