apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: dev
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: dev
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
