apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-demo-cicd
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: giangle197/nginx_lab:v1
        ports:
          - containerPort: 8080
            protocol: TCP